### ISSUE TITLE
Support Data Lake Private Endpoints

### ISSUE THREAD

**Issue by rkistner** [pulumi/pulumi-mongodbatlas#116]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Atlas Data Lake Private Endpoints use a different API different from standard cluster Private Endpoints. Could support be added for this?

API docs:

https://docs.mongodb.com/datalake/reference/api/dataLakes-private-link-create-one/

Terraform resource: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/privatelink_endpoint_service_adl

Added in the terraform provider here: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/640

### Affected area/feature

Described above.

**Comment by jkodroff** [comment]
@rkistner Submitted a PR to add these resources (linked above). Will release as soon as possible.

**Comment by rkistner** [comment]
Thanks, works great!
