### ISSUE TITLE
Created NetworkPeering resources have default atlasCidrBlock values even when a different value is set

### ISSUE THREAD

**Issue by wbk** [pulumi/pulumi-mongodbatlas#128]
### What happened?

 I've been having an issue with the `atlasCidrBlock` in a managed mongodbatlas.NetworkPeering resource using the Node version of pulumi-mongodbatlas. The option seems to have no effect and the created resource seems always to have the default value of `192.168.248.0/21`

### Steps to reproduce

```
export const atlasPeer = new mongodbatlas.NetworkPeering('atlas-peer', {
  providerName: "AWS",
  awsAccountId: AWS_ACCOUNT_ID,
  vpcId: VPC_ID,
  projectId: ATLAS_PROJECT_ID,
  containerId: mongoCluster.containerId,
  accepterRegionName: AWS_REGION,
  routeTableCidrBlock: '10.11.0.0/16',
  atlasCidrBlock: '192.168.232.0/21',
});
```

### Expected Behavior

For the created resource to have an atlasCidrBlock of `192.168.232.0/21`

### Actual Behavior

The created resource has the default value of `192.168.248.0/21`

Of note, the stack output retains the desired value of `192.168.232.0/21`, even across `pulumi refresh` operations.

### Versions used

CLI          
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME          VERSION
aws           4.38.1
docker        3.2.0
mongodbatlas  3.3.0
mysql         3.1.0
nodejs        unknown
random        4.8.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @wbk 

I am sorry that this isn't more clear from our docs but it seems that the upstream provider stopped using `atlasCidrBlock` - there are no sets of examples now that use it. From [our docs](https://www.pulumi.com/registry/packages/mongodbatlas/api-docs/networkpeering/#example-with-aws-1), I can see that the example to create network peering with AWS will need the use of a `network_container` as follows:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as mongodbatlas from "@pulumi/mongodbatlas";

// Container example provided but not always required, 
// see network_container documentation for details. 
const testNetworkContainer = new mongodbatlas.NetworkContainer("testNetworkContainer", {
    projectId: local.project_id,
    atlasCidrBlock: "10.8.0.0/21",
    providerName: "AWS",
    regionName: "US_EAST_1",
});
// Create the peering connection request
const testNetworkPeering = new mongodbatlas.NetworkPeering("testNetworkPeering", {
    accepterRegionName: "us-east-1",
    projectId: local.project_id,
    containerId: "507f1f77bcf86cd799439011",
    providerName: "AWS",
    routeTableCidrBlock: "192.168.0.0/24",
    vpcId: "vpc-abc123abc123",
    awsAccountId: "abc123abc123",
});
// the following assumes an AWS provider is configured
// Accept the peering connection request
const peer = new aws.ec2.VpcPeeringConnectionAccepter("peer", {
    vpcPeeringConnectionId: testNetworkPeering.connectionId,
    autoAccept: true,
});

I hope this helps - I will raise it with the upstream provider that this parameter should be removed now that it is *never* referenced in their code

Paul
