### ISSUE TITLE
Preview failed: unrecognized resource type (Read): mongodbatlas:index/serverlessInstance:ServerlessInstance

### ISSUE THREAD

**Issue by rni34** [pulumi/pulumi-mongodbatlas#138]
### What happened?

I get this error when trying to import a serverless instance
Preview failed: unrecognized resource type (Read): mongodbatlas:index/serverlessInstance:ServerlessInstance

### Steps to reproduce

simply copy and paste the code from [here](https://www.pulumi.com/registry/packages/mongodbatlas/api-docs/serverlessinstance/#look-up) to import

Run
```pulumi import mongodbatlas:index/serverlessInstance:ServerlessInstance my_serverless_instance 1112222b3bf99403840e8934-MyServerlessInstance```

### Expected Behavior

import the serverless instance

### Actual Behavior

error: Preview failed: unrecognized resource type (Read): mongodbatlas:index/serverlessInstance:ServerlessInstance

### Versions used

$ pulumi about
CLI
Version      3.36.0
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME          VERSION
aws           5.3.0
awsx          1.0.0-beta.8
docker        3.2.0
mongodbatlas  3.4.0
python        unknown

Host
OS       amazon
Version  2
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.7.10'

Current Stack: dev

TYPE                                                    URN
mongodbatlas:index/project:Project                      urn:pulumi:dev::scm-pipeline::mongodbatlas:index/project:Project::pulumi_test
platform-dev

Found no pending operations associated with dev

Backend

URL            s3://scm-pulumi-backend
User           ec2-user
Organizations

Dependencies:
NAME                 VERSION
pip                  22.0.4
pulumi-awsx          1.0.0b8
pulumi-mongodbatlas  3.4.0
setuptools           62.1.0
wheel                0.37.1

### Additional context

I was looking at  [here](https://github.com/pulumi/pulumi-mongodbatlas/blob/fc662716b45d99b9098f2e12d1fbac87156fb61f/sdk/python/pulumi_mongodbatlas/__init__.py)
and could not find the package name for serverless instance, maybe it needs to be added here?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @rni34 

The serverless instance work only went live in v3.5.0 so you will need to ensure that is the version of the provider you are using

Paul

**Comment by rni34** [comment]
Thank you, I did not know that there was a new version released yesterday.
it's working now, sorry about that

**Comment by stack72** [comment]
Ah wonderful :) thank you for getting back to us so fast! Please do let us know if there are any issues
