### ISSUE TITLE
PrivateLinkEndpointService import doesn't work properly

### ISSUE THREAD

**Issue by domifish** [pulumi/pulumi-mongodbatlas#144]
### What happened?

Import PrivateLinkEndpointService following https://www.pulumi.com/registry/packages/mongodbatlas/api-docs/privatelinkendpointservice/ is broken

Import works well , but the privateLinkId generated in the stack file is incorrect.

### Steps to reproduce

1  run "pulumi import mongodbatlas:index/privateLinkEndpointService:PrivateLinkEndpointService

{atlas_project_name}_private_link_service  {atlas_project_id}--{atlas_private_link_id}--{atlas_endpoint_service_id}--AWS --yes"

2 run "pulumi preview"

3 output show "Diff" and the ressource is marked as "update"

### Expected Behavior

pulumi preview should not show diff and no update should be planned.

### Actual Behavior

3 output show "Diff" and the ressource is marked as "update"

### Output of `pulumi about`

CLI
Version      3.35.3   
Go Version   go1.17.11
Go Compiler  gc       

Plugins
NAME          VERSION
aws           5.2.0
command       0.1.0
mongodbatlas  3.5.0
python        unknown

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19042 Build 19042
Arch     x86_64

This project is written in python: executable='C:\Users\XXXXXX\AppData\Local\Programs\Python\Python39\python.exe' version='3.9.6'

Backend
Name           T0NFD
URL            s3://xxxxxxxxxxxxxxx/xxxxxxxxxxxxx/
User           XXXXX\XXXXX
Organizations

Dependencies:
NAME                 VERSION
boto3                1.24.61
pip                  21.1.3
pulumi-aws           5.2.0
pulumi-command       0.1.0
pulumi-mongodbatlas  3.5.0
requests-aws4auth    1.1.2
setuptools           56.0.0

Pulumi locates its logs in C:\Users\XXXXXX\AppData\Local\Temp\1 by default
warning: A new version of Pulumi is available. To upgrade from version '3.35.3' to '3.38.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

### Additional context

We've found out that in stack file there is a problem with the imported values.

In the block where the urn  is "index/privateLinkEndpointService:PrivateLinkEndpointService" :

*  When we import the privateLinkEndpointService:PrivateLinkEndpointService resource : 
In "inputs.privateLinkId"  and "outputs.privateLinkId" : the value is : 

the private Link Id from atlas.

* When we create a privateLinkEndpointService:PrivateLinkEndpointService  resource 
In "inputs.privateLinkId"  and "outputs.privateLinkId" : the value is the following combination :

{private_link_id_b64_str}:{private_link_id_value_b64_str}-{project_id_b64_str}:{project_id_value_b64_str}-{provider_name_b64_str}:${provider_name_value_b64_str}-{region_b64_str}:{region_value_b64_str}"

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @domifish - this is going to be really tricky for us to reproduce without seeing your code, since a diff would usually show up if your code for the imported resource isn't exactly describing the state of your resource. What is the nature of the diff you see?

Can you elaborate on what you mean by there's a problem with the imported values in the stack? What you describe sounds correct to me.

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll go ahead and close this issue as stale. Please open a new issue if the problem still persists and provide the details for us to reproduce it. Thank you!
