### ISSUE TITLE
cron GHA is broken

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-mongodbatlas#167]
### What happened?

https://github.com/pulumi/pulumi-mongodbatlas/actions/runs/3880682203

### Steps to reproduce

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Should be fixed in https://github.com/pulumi/pulumi-mongodbatlas/pull/168
