### ISSUE TITLE
How to get the current client config?

### ISSUE THREAD

**Issue by rhuanbarreto** [pulumi/pulumi-mongodbatlas#201]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Similar to how the [azure-native](https://www.pulumi.com/registry/packages/azure-native/api-docs/authorization/getclientconfig/) library does, how can I do the same in this library? 
It's probably worth a docs on how to do it.

### Affected area/feature

SDK

**Comment by guineveresaenger** [comment]
Hi @rhuanbarreto - thank you for filing this issue.

Can you let us know a bit more what specifically you are looking for? The azure-native example is for a very specific Resource - is there a specific resource you had in mind?

For basic provider configuration, please see https://www.pulumi.com/registry/packages/mongodbatlas/installation-configuration/, if that's more what you're looking for.

**Comment by rhuanbarreto** [comment]
I managed to solve it by doing the following:

```typescript
export const atlasLibraryConfig = new Config("mongodbatlas");
const atlasPrivateKey = atlasLibraryConfig.getSecret("privateKey");
const atlasPublicKey = atlasLibraryConfig.getSecret("publicKey");
```
