### ISSUE TITLE
Add support for `mongoDbMajorVersion` == '6.0' and '7.0' for provisioning`AdvancedCluster` objects

### ISSUE THREAD

**Issue by AnEddieAllen** [pulumi/pulumi-mongodbatlas#363]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently wanting to upgrade Mongo Atlas cluster versions to versions 6 and 7 with pulumi. According to the docs, only major cluster versions up to 5.0 supported https://www.pulumi.com/registry/packages/mongodbatlas/api-docs/advancedcluster/#mongodbmajorversion_nodejs

**Comment by iwahbe** [comment]
Hi @AnEddieAllen. Thanks for opening an issue. This provider is bridged from the upstream TF provider maintained by mongodb: https://github.com/mongodb/terraform-provider-mongodbatlas. We support setting `mongoDbMajorVersion` to higher values as soon as they do.

**Comment by AnEddieAllen** [comment]
Hi @iwahbe  thanks for getting back to me. In the end I was able to upgrade to version 6 and then 7 with pulumi after having upgraded to `"@pulumi/mongodbatlas": "^3.13.0"` . It would still be good to reflect this in the [documentation](https://www.pulumi.com/registry/packages/mongodbatlas/api-docs/advancedcluster/#mongodbmajorversion_nodejs) though
