### ISSUE TITLE
Migration to Flex Clusters

### ISSUE THREAD

**Issue by hffmnn** [pulumi/pulumi-mongodbatlas#623]
Hi there.

In the last weeks MongoDB started to inform customers about changes to the types of clusters they offer.

> Active M2, M5, and Serverless clusters will be automatically migrated to a Flex cluster, beginning January 2025 for M2/M5 and March 2025 for Serverless. MongoDB has planned this to be a seamless transition with an emphasis on:
    Zero impact on your operations
    No changes to your connection strings or application code
    Seamless transition to a flexible, tiered pricing model (see pricing details above)
 
and

> Customers can use existing programmatic methods to create M2, M5 and Serverless tier clusters until January 2025. However, the behavior of these programmatic methods is scheduled to change in January 2025 as set forth below:
   M2/M5 APIs will create Flex clusters instead of M2 or M5 clusters.  
    Serverless instances APIs will create Flex clusters instead of Serverless instances
Please note that these programmatic methods will be EOL’d in January 2026. 

Here is a link to the documentation for IaC tools: https://www.mongodb.com/docs/atlas/flex-migration/ which also states:
> API endpoints for [Serverless Instances](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tagServerless-Instances) will begin managing Flex clusters in January of 2025. You can continue managing your existing Serverless instances using these APIs. Existing Serverless instances will be migrated to Free clusters, Flex clusters, or Dedicated clusters, according to your usage, after March 2025

I am using a Serverless Instance via `pulumi-mongodbatlas` => https://www.pulumi.com/registry/packages/mongodbatlas/api-docs/serverlessinstance/

Looking at the docs I mentioned, I already wonder: Serverless Instances get migrated in March 2025 but the API Endpoints start managing Flex Clusters in January 2025. What happens if I do a deployment in February 2025?

Are there any plans on how these changes will be implemented in this package (e.g. will there still be the same `ServerlessInstance` that does the correct calls to generate a flex cluster or will this be a breaking change)? Will there be a guide on how to migrate? Can this be handled by pulumi without a complete redeployment (which would be "the horror")?

Thanks in advance.

**Comment by ringods** [comment]
@hffmnn this provider bridges the upstream Terraform provider. The Mongo team is busy implementing support for Flex clusters:

https://github.com/search?q=repo%3Amongodb%2Fterraform-provider-mongodbatlas+flex&type=pullrequests

Looking at the merge date of these pull requests, these didn't make it in the latest release of their provider. Once the Mongo team creates a new release, the Pulumi team can update this provider too.
