### ISSUE TITLE
sdk/go.mod not bumped to v2

### ISSUE THREAD

**Issue by jacobfoard** [pulumi/pulumi-mongodbatlas#75]
It looks like when v2 was release the sdk/go.mod was missed. The docs were [updated](https://github.com/pulumi/pulumi-mongodbatlas/commit/af7a4bad408a4639365600e31a2b793c9fa8f2d4#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), but running the command from the docs results in an error due to the sdk/go.mod file not having the `v2` suffix.

```
❯ go get github.com/pulumi/pulumi-mongodbatlas/sdk/v2/go/...

go get: module github.com/pulumi/pulumi-mongodbatlas/sdk@upgrade found (v1.7.0), but does not contain packages matching github.com/pulumi/pulumi-mongodbatlas/sdk/v2/go/...
```

**Comment by stack72** [comment]
Hey @jacobfoard 

Apologies for this - I will make a release for this right now

Paul

**Comment by stack72** [comment]
Hey @jacobfoard 

Take v2.0.1 for a spin and let me know if there are any other issues

Paul

**Comment by jacobfoard** [comment]
@stack72 Just verified, looks good! 

Thanks so much for the quick response!

**Comment by stack72** [comment]
My apologies for it not being correct to start with :)
