### ISSUE TITLE
`go.mod` is set to `v2` sdk instead of `v3`

### ISSUE THREAD

**Issue by jacobfoard** [pulumi/pulumi-mongodbatlas#92]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
`go.mod` needs to be updated for `v3` sdk.

### Steps to reproduce

1.`go get github.com/pulumi/pulumi-mongodbatlas/sdk/v3`

Expected: Updated to latest version
Actual:
```
go: downloading github.com/pulumi/pulumi-mongodbatlas v1.7.0
go: downloading github.com/pulumi/pulumi-mongodbatlas/sdk v1.7.0
go: downloading github.com/pulumi/pulumi-mongodbatlas v3.1.0+incompatible
go get: module github.com/pulumi/pulumi-mongodbatlas/sdk@upgrade found (v1.7.0), but does not contain package github.com/pulumi/pulumi-mongodbatlas/sdk/v3
```

**Comment by stack72** [comment]
Hi @jacobfoard 

I am so sorry about this - I have opened a PR to fix and will release it within the next hour - it will be v3.1.1 as it's a patch to the current version

Paul
